[package]
name = "bonfire"
version = "0.1.0"
edition = "2018"

[dependencies]
bonfire_shared = { path = "../bonfire_shared" }
bincode = "1.3.3"
termion = "1.5.6"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
